# Support Vector Machine - Multiclass Classification 

In this notebook, we use Scikit-Learn's svm.SVC class to perform multi-class classification.

By default the SVC class uses <strong>One-versus-One (OvO)</strong> technique when we train it on more than two classes.

In [1]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Dataset


We will use the iris dataset, which is a multivariate data set. 

This is a famous dataset that contains the sepal and petal length and width of 150 iris flowers of three different species: Iris-Setosa, Iris-Versicolor, and Iris-Virginica

There are 4 features: 
- sepal length (cm)
- sepal width (cm)
- petal length (cm)
- petal width (cm)

Total number of samples: 150

The dataset is also known as Fisher's Iris data set as it was introduced by the British statistician and biologist Ronald Fisher in his 1936 paper "The use of multiple measurements in taxonomic problems as an example of linear discriminant analysis".


<img src="https://cse.unl.edu/~hasan/IrisFlowers.png" width=800, height=400>

## Explore The Dataset

In [2]:
iris = load_iris()

# See the key values
print("\nKey Values: \n", list(iris.keys()))

# The feature names
print("\nFeature Names: \n", list(iris.feature_names))

# The target names
print("\nTarget Names: \n", list(iris.target_names))

# The target values (codes)
#print("\nTarget Values: \n", list(iris.target))


Key Values: 
 ['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

Feature Names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names: 
 ['setosa', 'versicolor', 'virginica']


## Create Data Matrix (X) and the Label Array (y)


In [3]:
# For the experimentation we use two features
X = iris["data"]

# Target Array
y = iris["target"]

print(X.shape)
print(y.shape)

print("\nX data type: ", X.dtype)
print("y data type: ", y.dtype)

(150, 4)
(150,)

X data type:  float64
y data type:  int64


## Split Data Into Training and Test Sets

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=2)

## Standardize the Data

In [5]:
scaler = StandardScaler()

# Fit on training set only.
scaler.fit(X_train)

# Apply transform to both the training set and the test set.
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Train the SVC Model

We don't perform hyperparameter tuning to keep our presentation simple.

In [6]:
svm_clf = SVC()

svm_clf.fit(X_train, y_train)
y_predicted = svm_clf.predict(X_train)

accuracy_score = np.mean(y_predicted == y_train)
print("\nTrain Accuracy: ", accuracy_score)

print("\nTrain Confusion Matrix:")
print(confusion_matrix(y_train, y_predicted))


Train Accuracy:  0.9666666666666667

Train Confusion Matrix:
[[36  0  0]
 [ 0 40  2]
 [ 0  2 40]]


## Evaluate the Model using Test Data

In [7]:
y_test_predicted = svm_clf.predict(X_test)

accuracy_score_test = np.mean(y_test_predicted == y_test)
print("\nTest Accuracy: ", accuracy_score_test)

print("\nTest Confusion Matrix:")
print(confusion_matrix(y_test, y_test_predicted))


Test Accuracy:  0.9666666666666667

Test Confusion Matrix:
[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
